DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS identificador;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ci INTEGER UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE identificador (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ci INTEGER UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  birth_date TEXT NOT NULL,
  residencia TEXT NOT NULL
);